import * as util from '@/util'

export function useUtil() {
  return {
    bufToString: util.bufToString,
    xToBuffer: util.xToBuffer,
    bufToBinary: util.bufToBinary,
    binaryStringToBuffer: util.binaryStringToBuffer,
    isJson: util.isJson,
    zippedToString: util.zippedToString,
    copyToClipboard: util.copyToClipboard,
    cutString: util.cutString,
    bufToQuotation: util.bufToQuotation,
    bufToHex: util.bufToHex,
    bufVisible: util.bufVisible,
    isPHPSerialize: util.isPHPSerialize,
    isJavaSerialize: util.isJavaSerialize,
    isPickle: util.isPickle,
    isMsgpack: util.isMsgpack,
    isBrotli: util.isBrotli,
    isGzip: util.isGzip,
    isDeflate: util.isDeflate,
    isDeflateRaw: util.isDeflateRaw,
    isProtobuf: util.isProtobuf,
    base64Encode: util.base64Encode,
    base64Decode: util.base64Decode,
    humanFileSize: util.humanFileSize,
    leftTime: util.leftTime,
    cloneObjWithBuff: util.cloneObjWithBuff,
    keysToList: util.keysToList,
    keysToTree: util.keysToTree,
    formatTreeData: util.formatTreeData,
    sortKeysAndFolder: util.sortKeysAndFolder,
    sortByTreeNodes: util.sortByTreeNodes,
    debounce: util.debounce,
    randomString: util.randomString,
    createAndDownloadFile: util.createAndDownloadFile,
    arrayChunk: util.arrayChunk,
  }
}
